CREATE TABLE Users (
    Id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    HashedPassword VARCHAR(100) NOT NULL,
    CreatedTimestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (Id)
);

CREATE TABLE Diary (
    Id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    UserId INT UNSIGNED NOT NULL,
    Title VARCHAR(255) NOT NULL,
    Content TEXT DEFAULT NULL,
    IsPublished BOOL NOT NULL DEFAULT FALSE,
    CreatedTimestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PublishedTimestamp TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (Id),
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);